name: Install dependencies
description: Install React Native dependencies (NodeJS packages/Gems/Cocoapods) with caching for each.

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'
        bundler: '1.17.2'

    - name: Update RubyGems and install dependencies
      shell: bash
      run: |
        gem update --system 3.3.22
        gem install bundler -v '1.17.2'
        bundle config set --local path 'vendor/bundle'
        bundle config set --local force_ruby_platform true
        bundle install --jobs 4 --retry 3

    - name: Cache node_modules
      uses: actions/cache@v3
      id: modules-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install node_modules if necessary
      if: steps.modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm install
