name: Android Build to AppDistribution
on:
  pull_request:
    branches:
      - development
    types:
      - closed
  workflow_dispatch:

env:
  GITHUB_EMAIL: "makota.tv@gmail.com"
  GITHUB_USER: "Taras Github"

jobs:
  build-prod-android:
    if: github.event.pull_request.merged == true
    name: Build & ship android prod app
    runs-on: ubuntu-latest
    steps:
      # Step 1: Setup java and node
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: development

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set JAVA_HOME to JDK 17
        shell: bash
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

      - name: Validate Java Installation
        shell: bash
        run: java -version && echo "JAVA_HOME is set to $JAVA_HOME"

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        shell: bash
        run: cd android && chmod +x ./gradlew

      - name: Set up NODE
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      # Step 3: Install node packages
      - name: Install node modules
        run: npm ci
        env:
          CI: true
      # Step 4: Setup ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'
          bundler: '1.17.2'
      # Step 5: Install bundler, and fastlane
      - name: Install Fastlane
        run: |
          gem update --system 3.3.22
          gem install bundler -v '1.17.2'
          cd android && bundle install && cd ../
        env:
          CI: true

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./android/app/google-services.json

      # Step 8: Fastlane build android
      - name : Build android App via fastlane
        run : fastlane firebase platform:android

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
